### ISSUE TITLE
Blood Mark Drops on low level mobs

### ISSUE THREAD

**Issue by Dimsumexpress** [Kashim1082/4.8-Bug-reports#15]
Hi

Just wondering about the blood mark drops on low level mobs, it is dropping between 1-4.
Below are two screenshots and it dropped on lvl 43 mobs.
https://gyazo.com/88c1abf05829cb64706bef548c3e604d
https://gyazo.com/198bd0df4f3bebf33ef90bff888f8fce

Bachiko also noted he killed Bakarma and got blood marks.

**Comment by Dimsumexpress** [comment]
nvm.. received a response on discord this is an event and Kashim is going to disable it.

**Comment by Kashim1082** [comment]
Disabled it ! 
Thanks for reporting ^_^
