### ISSUE TITLE
Quest Mobs glitching

### ISSUE THREAD

**Issue by Dimsumexpress** [Kashim1082/4.8-Bug-reports#17]
Hi

Quest mobs seems to glitch by a lot. Even though you have already killed it (showing 0hp) and that you can loot it, but you can't because it still appears to be alive. 

Please see my screenshot: https://gyazo.com/a2727f231491d48222940f71f08545c5

Thanks!

**Comment by Kashim1082** [comment]
Hey !

Are you in a group or using the kill command ?

Thanks !

**Comment by Dimsumexpress** [comment]
yes, but they were not in the area I was in when I killed the mob
