### ISSUE TITLE
Food Reward x100 did not stack <Expert Noble Spicy Banquet Food>

### ISSUE THREAD

**Issue by Dimsumexpress** [Kashim1082/4.8-Bug-reports#22]
Hi

Received x100 of the <Expert Noble Spicy Banquet Food>  but this food did not stack, so basically occupying the entire inventory space.

The other food <Tasty Horned Dragon Emperor's Savory Food>x100 did stack.

Screenshot: https://gyazo.com/6a656637ec2c4cd20345dc202166be7b

**Comment by Kashim1082** [comment]
Fixed.
