### ISSUE TITLE
Lvl 65 Final Rewards/Survey

### ISSUE THREAD

**Issue by Dimsumexpress** [Kashim1082/4.8-Bug-reports#23]
Hi 
Hitting lvl 65, the final rewards:

Prestige Wings
5,000 Blood Marks
300 Major Crowns
2,000 Ceramium Medals
10,000 Kahrun Symbols
<Motion Card> The Dragon's Set
10,000 Ancient Coins
Flying Pagati

**Comment by Kashim1082** [comment]
Fixed.
