### ISSUE TITLE
Dragon Lord Refuge

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#27]
![image](https://user-images.githubusercontent.com/55855702/66268937-d1e7cf80-e818-11e9-9106-d1e84af7ba3f.png)
After killing Tiamat, these 2 wild npcs Kahrun appear
Also, the timer keeps running, even without the dungeon:
![image](https://user-images.githubusercontent.com/55855702/66268948-f2178e80-e818-11e9-9407-e8047baa6445.png)

**Comment by Kashim1082** [comment]
Fixed.
