### ISSUE TITLE
Quest mobs not spawning after flipping the camp - Katalam

### ISSUE THREAD

**Issue by Dimsumexpress** [Kashim1082/4.8-Bug-reports#31]
Flipped the Garren Forest Camp ..only spawned 4 that can be killed... rest appear to be friendly even though npcs are elyos.

Screenshot: https://gyazo.com/9bba44a503b8fc49e4fb22ba6b95fa8f

FYI... this seems to be common issue on all blood mark camps.
Quest mobs not spawning after flipping the camp.
Example:  https://gyazo.com/b9f0b4b9ac5dd9644a12eaa9faaa2de6

**Comment by Kashim1082** [comment]
Fixed.
