### ISSUE TITLE
Blood Mark Camps

### ISSUE THREAD

**Issue by XbachikoX** [Kashim1082/4.8-Bug-reports#36]
When you turn a camp over "all camps" you get 2 spots to kill mobs for the weekly's 1 spot is elyos not all the npc's turn so you can kill them. they stay to where you cant kill them like they are friendly 
![Aion0001](https://user-images.githubusercontent.com/56235649/66276038-bbfbfe00-e85c-11e9-80ff-008503353225.jpg)
 and the balaur spot they will not spawn or you get one mob to kill...
![Aion0007](https://user-images.githubusercontent.com/56235649/66276018-8b1bc900-e85c-11e9-8685-1c8160140a54.jpg)

IceThorn camp when you try to turn in quest - A Fierce Struggle- you get Load Fail id 23305
![Aion0008](https://user-images.githubusercontent.com/56235649/66276181-85bf7e00-e85e-11e9-8186-459aba2757db.jpg)

camps
Desolation and Starlit have a stigma/skill book vendor at both and you will get a load fail when you click on them 
Desolation -- agrahum
starlit -- geiravor
![Aion0009](https://user-images.githubusercontent.com/56235649/66276286-a3d9ae00-e85f-11e9-831a-75998ed3c15d.jpg)

also getting the event 40e armor drop every now and then from mobs and bosses
![Aion0005](https://user-images.githubusercontent.com/56235649/66276241-2dd54700-e85f-11e9-9748-d7ec4c9a3649.jpg)

These mobs shouldnt be dropping that low of items 
![Aion0010](https://user-images.githubusercontent.com/56235649/66276342-fc10b000-e85f-11e9-8ac9-e0e3db2da7ad.jpg)

**Comment by Kashim1082** [comment]
Fixed.
