### ISSUE TITLE
Npcs missing items

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#39]
![image](https://user-images.githubusercontent.com/55855702/66277354-6e3ec000-e873-11e9-8903-d09e0a426ff9.png)
Frode and Sejvina
"buy list is missing"

**Comment by Kashim1082** [comment]
Added buy list.
Requires test.

**Comment by Kashim1082** [comment]
fixed.

**Comment by cmarvulli** [comment]
Tested and working
