### ISSUE TITLE
Crushing The Conspiracy

### ISSUE THREAD

**Issue by LilliyaLunari** [Kashim1082/4.8-Bug-reports#5]
Level 20 Altgard final campaign is bugged once you go through the abyss gate. Upon entering the gate, there are no mobs, and no items to interact with. 
http://aion.mmorpg-life.com/quest/crushing-the-conspiracy/3403/
http://aiondatabase.net/us/quest/2022/
![Aion0011](https://user-images.githubusercontent.com/56207417/66261346-9fe35880-e799-11e9-8244-fadbcab02ec3.jpg)

**Comment by Kashim1082** [comment]
Added spawns.
Requires server restart & test.

**Comment by Kashim1082** [comment]
Tested and works.
