### ISSUE TITLE
Dark Poeta 

### ISSUE THREAD

**Issue by XbachikoX** [Kashim1082/4.8-Bug-reports#51]
Drana Lumps do not stun boss
![Aion0038](https://user-images.githubusercontent.com/56235649/66363029-d0babd80-e952-11e9-95da-3e3e10874725.jpg)

Some Mobs do not render correctly 
![Aion0037](https://user-images.githubusercontent.com/56235649/66363051-e4feba80-e952-11e9-9a14-04a4415bd33d.jpg)

**Comment by Kashim1082** [comment]
**Notes** 
Spaller Echta : 214880
Spectarl Avenger : 214860

**Comment by Kashim1082** [comment]
Fixed Spectral Avenger - to some degree.

**Comment by Kashim1082** [comment]
Fixed.
