### ISSUE TITLE
Empyrean crucible

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#54]
On stage 6, mobs stay in the ground after dying. They are targetable and receive damage:

![image](https://user-images.githubusercontent.com/55855702/66715729-04577680-ed9d-11e9-83bb-895ae91bfa0b.png)
![image](https://user-images.githubusercontent.com/55855702/66715733-0faaa200-ed9d-11e9-84ba-323c53ce481c.png)
![image](https://user-images.githubusercontent.com/55855702/66715739-189b7380-ed9d-11e9-97f2-defae5116a39.png)

Mobs bugged are :
Lich Necromancer
Elite Graveknight Warrior

Also, crucible ends at stage 9 round 3:
![image](https://user-images.githubusercontent.com/55855702/66715966-bdb74b80-ed9f-11e9-9742-049fddf8855f.png)

Video showing stages after this one:
https://youtu.be/uPKoQ7ZDz8Y?t=4295

**Comment by cmarvulli** [comment]
Count is bugged, but you can enter only 1 time (correct)
Actually you enter the second time, but get kicked out, so little bugged
![image](https://user-images.githubusercontent.com/55855702/66716022-35857600-eda0-11e9-8179-ed714696c83d.png)

**Comment by Kashim1082** [comment]
Fixed :
Lich Necromancer
Elite Graveknight Warrior

Changed method to load the stages.
Stages exist.
Requires testing.

**Comment by Kashim1082** [comment]
Fixed
