### ISSUE TITLE
Elyos campaign - Flying Reconnaissance

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#55]
Quest asks to lure Tursin Loudmouth Boss to Mereina, but the nearest Tursin resets before reaching her:

![image](https://user-images.githubusercontent.com/55855702/67146154-7aa51e80-f25e-11e9-827a-c7607112f182.png)

Maybe change the npc "range" to update the quest or increase the distance where Tursin resets

**Comment by Kashim1082** [comment]
increased range to 50

**Comment by cmarvulli** [comment]
Still need to increase range:
![image](https://user-images.githubusercontent.com/55855702/67524249-c274dd00-f686-11e9-9870-8663ed551de3.png)

![image](https://user-images.githubusercontent.com/55855702/67524237-b8eb7500-f686-11e9-955c-4505b930b9ed.png)
