### ISSUE TITLE
Npc missing

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#58]
Npc Kunberunerk should be there:
![image](https://user-images.githubusercontent.com/55855702/67150058-3418e980-f289-11e9-8b4a-a904295248ca.png)

**Comment by cmarvulli** [comment]
Actually it stays in one of these two locations according to time periods:
![image](https://user-images.githubusercontent.com/55855702/67151735-8a455700-f2a0-11e9-867b-41b25886d154.png)
Info:
https://aion.fandom.com/wiki/Kunberunerk

**Comment by Kashim1082** [comment]
<spawn npc_id="798026" respawn_time="295">
            <temporary_spawn/>
            <spot x="1824.54" y="2187.58" z="528.766" h="91">
                <temporary_spawn spawn_time="22.*.*" despawn_time="8.*.*"/>
            </spot>
            <spot x="1968.0" y="1768.0" z="576.7586" h="60">
                <temporary_spawn spawn_time="10.*.*" despawn_time="20.*.*"/>
            </spot>
        </spawn>

Spawn exists.
Closing the ticket.
