### ISSUE TITLE
Garrisons in Katalam/Danaria

### ISSUE THREAD

**Issue by LilliyaLunari** [Kashim1082/4.8-Bug-reports#6]
I haven't tested any of the garrisons other than Hadradim's Watch, but they seem to be working incorrectly to a degree. Miya killed all the elyos NPC's at Hadradim's Watch (no warcaptain, which is required for the camp to flip) and for some reason, Asmo NPC's began to spawn. The camp's map icon did not update though, and was still showing as Elyos. The Asmo Food merchants, Soul Healer, General Goods, and Special Vendor all spawned just from the Elyos NPC's being killed.

![Screenshot_1](https://user-images.githubusercontent.com/56207417/66262048-e7241600-e7a6-11e9-84d7-51274083dd3f.png)

 The Elyos camp guards continued to spawn until the Elyos Warcaptain finally spawned and was killed. Upon killing the Warcaptain the camp flipped somewhat as it should have. I say somewhat because there are NPC's here that are on top of each other and out of place.  

![Screenshot_2](https://user-images.githubusercontent.com/56207417/66262050-ed19f700-e7a6-11e9-9b7d-554565b82471.png)

This is certainly not how the garrisons are supposed to function.

**Comment by Kashim1082** [comment]
Changed spawn method.
Requires test.

**Comment by Kashim1082** [comment]
Tested and fixed.

**Comment by Kashim1082** [comment]
Attacking faction needs special identifier for attacking team.

**Comment by Kashim1082** [comment]
Fixed.
