### ISSUE TITLE
Sulla's startling discovery - campaign

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#61]
Step Examine the Traveller's Bag - bag not on the room:
![image](https://user-images.githubusercontent.com/55855702/67163769-478b8980-f349-11e9-8ca9-743eaca7e759.png)

Reference: http://aion.mmorpg-life.com/quest_images_screenshot/10023/Sulla_s_Startling_Discovery_16_0_Aion0019.jpg/

Bag location right now:
![image](https://user-images.githubusercontent.com/55855702/67163782-76096480-f349-11e9-9e20-7f029496c890.png)

**Comment by Kashim1082** [comment]
Fixed.

**Comment by cmarvulli** [comment]
Tested and working, but the traveller bag spawns after killing Zhanim....I think it would be already in the room (check location in the reference link i've sent....its not in the midlle)
