### ISSUE TITLE
It's better! It's an obelisk! - campaign

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#62]
Aetheric field generator inside Beshmundir Temple is bugged: it keeps reseting from combat (impossible to kill without gm skill) and cant be looted either:
![image](https://user-images.githubusercontent.com/55855702/67164360-11053d00-f350-11e9-8b96-eb642a8e55e5.png)
![image](https://user-images.githubusercontent.com/55855702/67164374-2c704800-f350-11e9-9d1e-4531c6069ced.png)

Also, I guess this mob Traitor Kumbanda should not be there overlapping the generator:
![image](https://user-images.githubusercontent.com/55855702/67164383-4e69ca80-f350-11e9-8cb1-00152cded262.png)

Using //kill on him, a cinematic is launched.

Database confirms its location there (weird):
http://aiondatabase.net/us/npc/799342/

Reference for generator:
https://youtu.be/cIWCJWNnJBc?t=434

**Comment by Kashim1082** [comment]
Fixed.
and moved npc.

**Comment by cmarvulli** [comment]
Tested and working
