### ISSUE TITLE
Guards with wrong textures

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#64]
ID's on pictures
![image](https://user-images.githubusercontent.com/55855702/67165538-ad354100-f35c-11e9-9c21-648c71d76945.png)
![image](https://user-images.githubusercontent.com/55855702/67165549-c1793e00-f35c-11e9-9270-0af1953fc481.png)

**Comment by Kashim1082** [comment]
Fixed.

**Comment by cmarvulli** [comment]
You got the wrong textures to fix haha:

Sentinels with ID 209051 should get texture from ID 209056
Detachments with ID 209101 should get texture from ID 209008

**Comment by Kashim1082** [comment]
Fixed.
