### ISSUE TITLE
Powering On - campaing

### ISSUE THREAD

**Issue by cmarvulli** [Kashim1082/4.8-Bug-reports#9]
![image](https://user-images.githubusercontent.com/55855702/66262558-2b201680-e7b9-11e9-83dd-328de2f5b3fd.png)
The right portal is not there
Check the youtube video:
https://www.youtube.com/watch?v=QA4_O3_Rwk0

**Comment by Kashim1082** [comment]
Changed spawn method of the portal.

**Comment by Kashim1082** [comment]
Fixed

**Comment by cmarvulli** [comment]
Tested and working
